/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedParentRouteImport } from './routes/_authed/parent'
import { Route as AuthedProfilesRouteImport } from './routes/_authed/profiles'
import { Route as AuthedParentIndexRouteImport } from './routes/_authed/parent/index'
import { Route as AuthedParentKidsRouteImport } from './routes/_authed/parent/kids'
import { Route as AuthedParentSettingsRouteImport } from './routes/_authed/parent/settings'
import { Route as AuthedPlayChildIdRouteImport } from './routes/_authed/play/$childId'
import { Route as AuthedParentListsListIdRouteImport } from './routes/_authed/parent/lists.$listId'
import { Route as AuthedParentProgressChildIdRouteImport } from './routes/_authed/parent/progress.$childId'
import { Route as AuthedPlayChildIdIndexRouteImport } from './routes/_authed/play/$childId/index'
import { Route as AuthedPlayChildIdResultsRouteImport } from './routes/_authed/play/$childId/results'
import { Route as AuthedPlayChildIdRoundListIdModeRouteImport } from './routes/_authed/play/$childId/round.$listId.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedParentRoute = AuthedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfilesRoute = AuthedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentIndexRoute = AuthedParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentKidsRoute = AuthedParentKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentSettingsRoute = AuthedParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedPlayChildIdRoute = AuthedPlayChildIdRouteImport.update({
  id: '/play/$childId',
  path: '/play/$childId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentListsListIdRoute = AuthedParentListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentProgressChildIdRoute =
  AuthedParentProgressChildIdRouteImport.update({
    id: '/progress/$childId',
    path: '/progress/$childId',
    getParentRoute: () => AuthedParentRoute,
  } as any)
const AuthedPlayChildIdIndexRoute = AuthedPlayChildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPlayChildIdRoute,
} as any)
const AuthedPlayChildIdResultsRoute =
  AuthedPlayChildIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdRoundListIdModeRoute =
  AuthedPlayChildIdRoundListIdModeRouteImport.update({
    id: '/round/$listId/$mode',
    path: '/round/$listId/$mode',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parent': typeof AuthedParentRouteWithChildren
  '/profiles': typeof AuthedProfilesRoute
  '/parent/kids': typeof AuthedParentKidsRoute
  '/parent/settings': typeof AuthedParentSettingsRoute
  '/play/$childId': typeof AuthedPlayChildIdRouteWithChildren
  '/parent/': typeof AuthedParentIndexRoute
  '/parent/lists/$listId': typeof AuthedParentListsListIdRoute
  '/parent/progress/$childId': typeof AuthedParentProgressChildIdRoute
  '/play/$childId/results': typeof AuthedPlayChildIdResultsRoute
  '/play/$childId/': typeof AuthedPlayChildIdIndexRoute
  '/play/$childId/round/$listId/$mode': typeof AuthedPlayChildIdRoundListIdModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles': typeof AuthedProfilesRoute
  '/parent/kids': typeof AuthedParentKidsRoute
  '/parent/settings': typeof AuthedParentSettingsRoute
  '/parent': typeof AuthedParentIndexRoute
  '/parent/lists/$listId': typeof AuthedParentListsListIdRoute
  '/parent/progress/$childId': typeof AuthedParentProgressChildIdRoute
  '/play/$childId/results': typeof AuthedPlayChildIdResultsRoute
  '/play/$childId': typeof AuthedPlayChildIdIndexRoute
  '/play/$childId/round/$listId/$mode': typeof AuthedPlayChildIdRoundListIdModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/parent': typeof AuthedParentRouteWithChildren
  '/_authed/profiles': typeof AuthedProfilesRoute
  '/_authed/parent/kids': typeof AuthedParentKidsRoute
  '/_authed/parent/settings': typeof AuthedParentSettingsRoute
  '/_authed/play/$childId': typeof AuthedPlayChildIdRouteWithChildren
  '/_authed/parent/': typeof AuthedParentIndexRoute
  '/_authed/parent/lists/$listId': typeof AuthedParentListsListIdRoute
  '/_authed/parent/progress/$childId': typeof AuthedParentProgressChildIdRoute
  '/_authed/play/$childId/results': typeof AuthedPlayChildIdResultsRoute
  '/_authed/play/$childId/': typeof AuthedPlayChildIdIndexRoute
  '/_authed/play/$childId/round/$listId/$mode': typeof AuthedPlayChildIdRoundListIdModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parent'
    | '/profiles'
    | '/parent/kids'
    | '/parent/settings'
    | '/play/$childId'
    | '/parent/'
    | '/parent/lists/$listId'
    | '/parent/progress/$childId'
    | '/play/$childId/results'
    | '/play/$childId/'
    | '/play/$childId/round/$listId/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profiles'
    | '/parent/kids'
    | '/parent/settings'
    | '/parent'
    | '/parent/lists/$listId'
    | '/parent/progress/$childId'
    | '/play/$childId/results'
    | '/play/$childId'
    | '/play/$childId/round/$listId/$mode'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/parent'
    | '/_authed/profiles'
    | '/_authed/parent/kids'
    | '/_authed/parent/settings'
    | '/_authed/play/$childId'
    | '/_authed/parent/'
    | '/_authed/parent/lists/$listId'
    | '/_authed/parent/progress/$childId'
    | '/_authed/play/$childId/results'
    | '/_authed/play/$childId/'
    | '/_authed/play/$childId/round/$listId/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/parent': {
      id: '/_authed/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthedParentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profiles': {
      id: '/_authed/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthedProfilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent/': {
      id: '/_authed/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthedParentIndexRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/kids': {
      id: '/_authed/parent/kids'
      path: '/kids'
      fullPath: '/parent/kids'
      preLoaderRoute: typeof AuthedParentKidsRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/settings': {
      id: '/_authed/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof AuthedParentSettingsRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/play/$childId': {
      id: '/_authed/play/$childId'
      path: '/play/$childId'
      fullPath: '/play/$childId'
      preLoaderRoute: typeof AuthedPlayChildIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent/lists/$listId': {
      id: '/_authed/parent/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/parent/lists/$listId'
      preLoaderRoute: typeof AuthedParentListsListIdRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/progress/$childId': {
      id: '/_authed/parent/progress/$childId'
      path: '/progress/$childId'
      fullPath: '/parent/progress/$childId'
      preLoaderRoute: typeof AuthedParentProgressChildIdRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/play/$childId/': {
      id: '/_authed/play/$childId/'
      path: '/'
      fullPath: '/play/$childId/'
      preLoaderRoute: typeof AuthedPlayChildIdIndexRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/results': {
      id: '/_authed/play/$childId/results'
      path: '/results'
      fullPath: '/play/$childId/results'
      preLoaderRoute: typeof AuthedPlayChildIdResultsRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/round/$listId/$mode': {
      id: '/_authed/play/$childId/round/$listId/$mode'
      path: '/round/$listId/$mode'
      fullPath: '/play/$childId/round/$listId/$mode'
      preLoaderRoute: typeof AuthedPlayChildIdRoundListIdModeRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
  }
}

interface AuthedParentRouteChildren {
  AuthedParentKidsRoute: typeof AuthedParentKidsRoute
  AuthedParentSettingsRoute: typeof AuthedParentSettingsRoute
  AuthedParentIndexRoute: typeof AuthedParentIndexRoute
  AuthedParentListsListIdRoute: typeof AuthedParentListsListIdRoute
  AuthedParentProgressChildIdRoute: typeof AuthedParentProgressChildIdRoute
}

const AuthedParentRouteChildren: AuthedParentRouteChildren = {
  AuthedParentKidsRoute: AuthedParentKidsRoute,
  AuthedParentSettingsRoute: AuthedParentSettingsRoute,
  AuthedParentIndexRoute: AuthedParentIndexRoute,
  AuthedParentListsListIdRoute: AuthedParentListsListIdRoute,
  AuthedParentProgressChildIdRoute: AuthedParentProgressChildIdRoute,
}

const AuthedParentRouteWithChildren = AuthedParentRoute._addFileChildren(
  AuthedParentRouteChildren,
)

interface AuthedPlayChildIdRouteChildren {
  AuthedPlayChildIdResultsRoute: typeof AuthedPlayChildIdResultsRoute
  AuthedPlayChildIdIndexRoute: typeof AuthedPlayChildIdIndexRoute
  AuthedPlayChildIdRoundListIdModeRoute: typeof AuthedPlayChildIdRoundListIdModeRoute
}

const AuthedPlayChildIdRouteChildren: AuthedPlayChildIdRouteChildren = {
  AuthedPlayChildIdResultsRoute: AuthedPlayChildIdResultsRoute,
  AuthedPlayChildIdIndexRoute: AuthedPlayChildIdIndexRoute,
  AuthedPlayChildIdRoundListIdModeRoute: AuthedPlayChildIdRoundListIdModeRoute,
}

const AuthedPlayChildIdRouteWithChildren =
  AuthedPlayChildIdRoute._addFileChildren(AuthedPlayChildIdRouteChildren)

interface AuthedRouteChildren {
  AuthedParentRoute: typeof AuthedParentRouteWithChildren
  AuthedProfilesRoute: typeof AuthedProfilesRoute
  AuthedPlayChildIdRoute: typeof AuthedPlayChildIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedParentRoute: AuthedParentRouteWithChildren,
  AuthedProfilesRoute: AuthedProfilesRoute,
  AuthedPlayChildIdRoute: AuthedPlayChildIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
