/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedParentRouteImport } from './routes/_authed/parent'
import { Route as AuthedProfilesRouteImport } from './routes/_authed/profiles'
import { Route as AuthedParentIndexRouteImport } from './routes/_authed/parent/index'
import { Route as AuthedParentAdminRouteImport } from './routes/_authed/parent/admin'
import { Route as AuthedParentKidsRouteImport } from './routes/_authed/parent/kids'
import { Route as AuthedParentSettingsRouteImport } from './routes/_authed/parent/settings'
import { Route as AuthedPlayChildIdRouteImport } from './routes/_authed/play/$childId'
import { Route as AuthedParentListsListIdRouteImport } from './routes/_authed/parent/lists.$listId'
import { Route as AuthedParentProgressChildIdRouteImport } from './routes/_authed/parent/progress.$childId'
import { Route as AuthedPlayChildIdIndexRouteImport } from './routes/_authed/play/$childId/index'
import { Route as AuthedPlayChildIdResultsRouteImport } from './routes/_authed/play/$childId/results'
import { Route as AuthedPlayChildIdSpellingRouteImport } from './routes/_authed/play/$childId/spelling'
import { Route as AuthedPlayChildIdGamesIndexRouteImport } from './routes/_authed/play/$childId/games/index'
import { Route as AuthedPlayChildIdGamesGobbleRouteImport } from './routes/_authed/play/$childId/games/gobble'
import { Route as AuthedPlayChildIdMathIndexRouteImport } from './routes/_authed/play/$childId/math/index'
import { Route as AuthedPlayChildIdMathTopicRouteImport } from './routes/_authed/play/$childId/math/$topic'
import { Route as AuthedPlayChildIdGamesRoxyIndexRouteImport } from './routes/_authed/play/$childId/games/roxy/index'
import { Route as AuthedPlayChildIdGamesRoxyHomeRouteImport } from './routes/_authed/play/$childId/games/roxy/home'
import { Route as AuthedPlayChildIdGamesRoxyLooksRouteImport } from './routes/_authed/play/$childId/games/roxy/looks'
import { Route as AuthedPlayChildIdGamesRoxyTownRouteImport } from './routes/_authed/play/$childId/games/roxy/town'
import { Route as AuthedPlayChildIdRoundListIdModeRouteImport } from './routes/_authed/play/$childId/round.$listId.$mode'
import { Route as AuthedPlayChildIdGamesRoxyPlacePlaceIdRouteImport } from './routes/_authed/play/$childId/games/roxy/place.$placeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedParentRoute = AuthedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfilesRoute = AuthedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentIndexRoute = AuthedParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentAdminRoute = AuthedParentAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentKidsRoute = AuthedParentKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentSettingsRoute = AuthedParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedPlayChildIdRoute = AuthedPlayChildIdRouteImport.update({
  id: '/play/$childId',
  path: '/play/$childId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParentListsListIdRoute = AuthedParentListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AuthedParentRoute,
} as any)
const AuthedParentProgressChildIdRoute =
  AuthedParentProgressChildIdRouteImport.update({
    id: '/progress/$childId',
    path: '/progress/$childId',
    getParentRoute: () => AuthedParentRoute,
  } as any)
const AuthedPlayChildIdIndexRoute = AuthedPlayChildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPlayChildIdRoute,
} as any)
const AuthedPlayChildIdResultsRoute =
  AuthedPlayChildIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdSpellingRoute =
  AuthedPlayChildIdSpellingRouteImport.update({
    id: '/spelling',
    path: '/spelling',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesIndexRoute =
  AuthedPlayChildIdGamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesGobbleRoute =
  AuthedPlayChildIdGamesGobbleRouteImport.update({
    id: '/games/gobble',
    path: '/games/gobble',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdMathIndexRoute =
  AuthedPlayChildIdMathIndexRouteImport.update({
    id: '/math/',
    path: '/math/',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdMathTopicRoute =
  AuthedPlayChildIdMathTopicRouteImport.update({
    id: '/math/$topic',
    path: '/math/$topic',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesRoxyIndexRoute =
  AuthedPlayChildIdGamesRoxyIndexRouteImport.update({
    id: '/games/roxy/',
    path: '/games/roxy/',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesRoxyHomeRoute =
  AuthedPlayChildIdGamesRoxyHomeRouteImport.update({
    id: '/games/roxy/home',
    path: '/games/roxy/home',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesRoxyLooksRoute =
  AuthedPlayChildIdGamesRoxyLooksRouteImport.update({
    id: '/games/roxy/looks',
    path: '/games/roxy/looks',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesRoxyTownRoute =
  AuthedPlayChildIdGamesRoxyTownRouteImport.update({
    id: '/games/roxy/town',
    path: '/games/roxy/town',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdRoundListIdModeRoute =
  AuthedPlayChildIdRoundListIdModeRouteImport.update({
    id: '/round/$listId/$mode',
    path: '/round/$listId/$mode',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)
const AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute =
  AuthedPlayChildIdGamesRoxyPlacePlaceIdRouteImport.update({
    id: '/games/roxy/place/$placeId',
    path: '/games/roxy/place/$placeId',
    getParentRoute: () => AuthedPlayChildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parent': typeof AuthedParentRouteWithChildren
  '/profiles': typeof AuthedProfilesRoute
  '/parent/admin': typeof AuthedParentAdminRoute
  '/parent/kids': typeof AuthedParentKidsRoute
  '/parent/settings': typeof AuthedParentSettingsRoute
  '/play/$childId': typeof AuthedPlayChildIdRouteWithChildren
  '/parent/': typeof AuthedParentIndexRoute
  '/parent/lists/$listId': typeof AuthedParentListsListIdRoute
  '/parent/progress/$childId': typeof AuthedParentProgressChildIdRoute
  '/play/$childId/results': typeof AuthedPlayChildIdResultsRoute
  '/play/$childId/spelling': typeof AuthedPlayChildIdSpellingRoute
  '/play/$childId/': typeof AuthedPlayChildIdIndexRoute
  '/play/$childId/games/gobble': typeof AuthedPlayChildIdGamesGobbleRoute
  '/play/$childId/math/$topic': typeof AuthedPlayChildIdMathTopicRoute
  '/play/$childId/games/': typeof AuthedPlayChildIdGamesIndexRoute
  '/play/$childId/math/': typeof AuthedPlayChildIdMathIndexRoute
  '/play/$childId/games/roxy/home': typeof AuthedPlayChildIdGamesRoxyHomeRoute
  '/play/$childId/games/roxy/looks': typeof AuthedPlayChildIdGamesRoxyLooksRoute
  '/play/$childId/games/roxy/town': typeof AuthedPlayChildIdGamesRoxyTownRoute
  '/play/$childId/round/$listId/$mode': typeof AuthedPlayChildIdRoundListIdModeRoute
  '/play/$childId/games/roxy/': typeof AuthedPlayChildIdGamesRoxyIndexRoute
  '/play/$childId/games/roxy/place/$placeId': typeof AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles': typeof AuthedProfilesRoute
  '/parent/admin': typeof AuthedParentAdminRoute
  '/parent/kids': typeof AuthedParentKidsRoute
  '/parent/settings': typeof AuthedParentSettingsRoute
  '/parent': typeof AuthedParentIndexRoute
  '/parent/lists/$listId': typeof AuthedParentListsListIdRoute
  '/parent/progress/$childId': typeof AuthedParentProgressChildIdRoute
  '/play/$childId/results': typeof AuthedPlayChildIdResultsRoute
  '/play/$childId/spelling': typeof AuthedPlayChildIdSpellingRoute
  '/play/$childId': typeof AuthedPlayChildIdIndexRoute
  '/play/$childId/games/gobble': typeof AuthedPlayChildIdGamesGobbleRoute
  '/play/$childId/math/$topic': typeof AuthedPlayChildIdMathTopicRoute
  '/play/$childId/games': typeof AuthedPlayChildIdGamesIndexRoute
  '/play/$childId/math': typeof AuthedPlayChildIdMathIndexRoute
  '/play/$childId/games/roxy/home': typeof AuthedPlayChildIdGamesRoxyHomeRoute
  '/play/$childId/games/roxy/looks': typeof AuthedPlayChildIdGamesRoxyLooksRoute
  '/play/$childId/games/roxy/town': typeof AuthedPlayChildIdGamesRoxyTownRoute
  '/play/$childId/round/$listId/$mode': typeof AuthedPlayChildIdRoundListIdModeRoute
  '/play/$childId/games/roxy': typeof AuthedPlayChildIdGamesRoxyIndexRoute
  '/play/$childId/games/roxy/place/$placeId': typeof AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/parent': typeof AuthedParentRouteWithChildren
  '/_authed/profiles': typeof AuthedProfilesRoute
  '/_authed/parent/admin': typeof AuthedParentAdminRoute
  '/_authed/parent/kids': typeof AuthedParentKidsRoute
  '/_authed/parent/settings': typeof AuthedParentSettingsRoute
  '/_authed/play/$childId': typeof AuthedPlayChildIdRouteWithChildren
  '/_authed/parent/': typeof AuthedParentIndexRoute
  '/_authed/parent/lists/$listId': typeof AuthedParentListsListIdRoute
  '/_authed/parent/progress/$childId': typeof AuthedParentProgressChildIdRoute
  '/_authed/play/$childId/results': typeof AuthedPlayChildIdResultsRoute
  '/_authed/play/$childId/spelling': typeof AuthedPlayChildIdSpellingRoute
  '/_authed/play/$childId/': typeof AuthedPlayChildIdIndexRoute
  '/_authed/play/$childId/games/gobble': typeof AuthedPlayChildIdGamesGobbleRoute
  '/_authed/play/$childId/math/$topic': typeof AuthedPlayChildIdMathTopicRoute
  '/_authed/play/$childId/games/': typeof AuthedPlayChildIdGamesIndexRoute
  '/_authed/play/$childId/math/': typeof AuthedPlayChildIdMathIndexRoute
  '/_authed/play/$childId/games/roxy/home': typeof AuthedPlayChildIdGamesRoxyHomeRoute
  '/_authed/play/$childId/games/roxy/looks': typeof AuthedPlayChildIdGamesRoxyLooksRoute
  '/_authed/play/$childId/games/roxy/town': typeof AuthedPlayChildIdGamesRoxyTownRoute
  '/_authed/play/$childId/round/$listId/$mode': typeof AuthedPlayChildIdRoundListIdModeRoute
  '/_authed/play/$childId/games/roxy/': typeof AuthedPlayChildIdGamesRoxyIndexRoute
  '/_authed/play/$childId/games/roxy/place/$placeId': typeof AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parent'
    | '/profiles'
    | '/parent/admin'
    | '/parent/kids'
    | '/parent/settings'
    | '/play/$childId'
    | '/parent/'
    | '/parent/lists/$listId'
    | '/parent/progress/$childId'
    | '/play/$childId/results'
    | '/play/$childId/spelling'
    | '/play/$childId/'
    | '/play/$childId/games/gobble'
    | '/play/$childId/math/$topic'
    | '/play/$childId/games/'
    | '/play/$childId/math/'
    | '/play/$childId/games/roxy/home'
    | '/play/$childId/games/roxy/looks'
    | '/play/$childId/games/roxy/town'
    | '/play/$childId/round/$listId/$mode'
    | '/play/$childId/games/roxy/'
    | '/play/$childId/games/roxy/place/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profiles'
    | '/parent/admin'
    | '/parent/kids'
    | '/parent/settings'
    | '/parent'
    | '/parent/lists/$listId'
    | '/parent/progress/$childId'
    | '/play/$childId/results'
    | '/play/$childId/spelling'
    | '/play/$childId'
    | '/play/$childId/games/gobble'
    | '/play/$childId/math/$topic'
    | '/play/$childId/games'
    | '/play/$childId/math'
    | '/play/$childId/games/roxy/home'
    | '/play/$childId/games/roxy/looks'
    | '/play/$childId/games/roxy/town'
    | '/play/$childId/round/$listId/$mode'
    | '/play/$childId/games/roxy'
    | '/play/$childId/games/roxy/place/$placeId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/parent'
    | '/_authed/profiles'
    | '/_authed/parent/admin'
    | '/_authed/parent/kids'
    | '/_authed/parent/settings'
    | '/_authed/play/$childId'
    | '/_authed/parent/'
    | '/_authed/parent/lists/$listId'
    | '/_authed/parent/progress/$childId'
    | '/_authed/play/$childId/results'
    | '/_authed/play/$childId/spelling'
    | '/_authed/play/$childId/'
    | '/_authed/play/$childId/games/gobble'
    | '/_authed/play/$childId/math/$topic'
    | '/_authed/play/$childId/games/'
    | '/_authed/play/$childId/math/'
    | '/_authed/play/$childId/games/roxy/home'
    | '/_authed/play/$childId/games/roxy/looks'
    | '/_authed/play/$childId/games/roxy/town'
    | '/_authed/play/$childId/round/$listId/$mode'
    | '/_authed/play/$childId/games/roxy/'
    | '/_authed/play/$childId/games/roxy/place/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/parent': {
      id: '/_authed/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthedParentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profiles': {
      id: '/_authed/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthedProfilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent/': {
      id: '/_authed/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthedParentIndexRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/admin': {
      id: '/_authed/parent/admin'
      path: '/admin'
      fullPath: '/parent/admin'
      preLoaderRoute: typeof AuthedParentAdminRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/kids': {
      id: '/_authed/parent/kids'
      path: '/kids'
      fullPath: '/parent/kids'
      preLoaderRoute: typeof AuthedParentKidsRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/settings': {
      id: '/_authed/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof AuthedParentSettingsRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/play/$childId': {
      id: '/_authed/play/$childId'
      path: '/play/$childId'
      fullPath: '/play/$childId'
      preLoaderRoute: typeof AuthedPlayChildIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parent/lists/$listId': {
      id: '/_authed/parent/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/parent/lists/$listId'
      preLoaderRoute: typeof AuthedParentListsListIdRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/parent/progress/$childId': {
      id: '/_authed/parent/progress/$childId'
      path: '/progress/$childId'
      fullPath: '/parent/progress/$childId'
      preLoaderRoute: typeof AuthedParentProgressChildIdRouteImport
      parentRoute: typeof AuthedParentRoute
    }
    '/_authed/play/$childId/': {
      id: '/_authed/play/$childId/'
      path: '/'
      fullPath: '/play/$childId/'
      preLoaderRoute: typeof AuthedPlayChildIdIndexRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/results': {
      id: '/_authed/play/$childId/results'
      path: '/results'
      fullPath: '/play/$childId/results'
      preLoaderRoute: typeof AuthedPlayChildIdResultsRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/spelling': {
      id: '/_authed/play/$childId/spelling'
      path: '/spelling'
      fullPath: '/play/$childId/spelling'
      preLoaderRoute: typeof AuthedPlayChildIdSpellingRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/': {
      id: '/_authed/play/$childId/games/'
      path: '/games'
      fullPath: '/play/$childId/games/'
      preLoaderRoute: typeof AuthedPlayChildIdGamesIndexRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/gobble': {
      id: '/_authed/play/$childId/games/gobble'
      path: '/games/gobble'
      fullPath: '/play/$childId/games/gobble'
      preLoaderRoute: typeof AuthedPlayChildIdGamesGobbleRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/math/': {
      id: '/_authed/play/$childId/math/'
      path: '/math'
      fullPath: '/play/$childId/math/'
      preLoaderRoute: typeof AuthedPlayChildIdMathIndexRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/math/$topic': {
      id: '/_authed/play/$childId/math/$topic'
      path: '/math/$topic'
      fullPath: '/play/$childId/math/$topic'
      preLoaderRoute: typeof AuthedPlayChildIdMathTopicRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/roxy/': {
      id: '/_authed/play/$childId/games/roxy/'
      path: '/games/roxy'
      fullPath: '/play/$childId/games/roxy/'
      preLoaderRoute: typeof AuthedPlayChildIdGamesRoxyIndexRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/roxy/home': {
      id: '/_authed/play/$childId/games/roxy/home'
      path: '/games/roxy/home'
      fullPath: '/play/$childId/games/roxy/home'
      preLoaderRoute: typeof AuthedPlayChildIdGamesRoxyHomeRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/roxy/looks': {
      id: '/_authed/play/$childId/games/roxy/looks'
      path: '/games/roxy/looks'
      fullPath: '/play/$childId/games/roxy/looks'
      preLoaderRoute: typeof AuthedPlayChildIdGamesRoxyLooksRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/roxy/town': {
      id: '/_authed/play/$childId/games/roxy/town'
      path: '/games/roxy/town'
      fullPath: '/play/$childId/games/roxy/town'
      preLoaderRoute: typeof AuthedPlayChildIdGamesRoxyTownRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/round/$listId/$mode': {
      id: '/_authed/play/$childId/round/$listId/$mode'
      path: '/round/$listId/$mode'
      fullPath: '/play/$childId/round/$listId/$mode'
      preLoaderRoute: typeof AuthedPlayChildIdRoundListIdModeRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
    '/_authed/play/$childId/games/roxy/place/$placeId': {
      id: '/_authed/play/$childId/games/roxy/place/$placeId'
      path: '/games/roxy/place/$placeId'
      fullPath: '/play/$childId/games/roxy/place/$placeId'
      preLoaderRoute: typeof AuthedPlayChildIdGamesRoxyPlacePlaceIdRouteImport
      parentRoute: typeof AuthedPlayChildIdRoute
    }
  }
}

interface AuthedParentRouteChildren {
  AuthedParentAdminRoute: typeof AuthedParentAdminRoute
  AuthedParentKidsRoute: typeof AuthedParentKidsRoute
  AuthedParentSettingsRoute: typeof AuthedParentSettingsRoute
  AuthedParentIndexRoute: typeof AuthedParentIndexRoute
  AuthedParentListsListIdRoute: typeof AuthedParentListsListIdRoute
  AuthedParentProgressChildIdRoute: typeof AuthedParentProgressChildIdRoute
}

const AuthedParentRouteChildren: AuthedParentRouteChildren = {
  AuthedParentAdminRoute: AuthedParentAdminRoute,
  AuthedParentKidsRoute: AuthedParentKidsRoute,
  AuthedParentSettingsRoute: AuthedParentSettingsRoute,
  AuthedParentIndexRoute: AuthedParentIndexRoute,
  AuthedParentListsListIdRoute: AuthedParentListsListIdRoute,
  AuthedParentProgressChildIdRoute: AuthedParentProgressChildIdRoute,
}

const AuthedParentRouteWithChildren = AuthedParentRoute._addFileChildren(
  AuthedParentRouteChildren,
)

interface AuthedPlayChildIdRouteChildren {
  AuthedPlayChildIdResultsRoute: typeof AuthedPlayChildIdResultsRoute
  AuthedPlayChildIdSpellingRoute: typeof AuthedPlayChildIdSpellingRoute
  AuthedPlayChildIdIndexRoute: typeof AuthedPlayChildIdIndexRoute
  AuthedPlayChildIdGamesGobbleRoute: typeof AuthedPlayChildIdGamesGobbleRoute
  AuthedPlayChildIdMathTopicRoute: typeof AuthedPlayChildIdMathTopicRoute
  AuthedPlayChildIdGamesIndexRoute: typeof AuthedPlayChildIdGamesIndexRoute
  AuthedPlayChildIdMathIndexRoute: typeof AuthedPlayChildIdMathIndexRoute
  AuthedPlayChildIdGamesRoxyHomeRoute: typeof AuthedPlayChildIdGamesRoxyHomeRoute
  AuthedPlayChildIdGamesRoxyLooksRoute: typeof AuthedPlayChildIdGamesRoxyLooksRoute
  AuthedPlayChildIdGamesRoxyTownRoute: typeof AuthedPlayChildIdGamesRoxyTownRoute
  AuthedPlayChildIdRoundListIdModeRoute: typeof AuthedPlayChildIdRoundListIdModeRoute
  AuthedPlayChildIdGamesRoxyIndexRoute: typeof AuthedPlayChildIdGamesRoxyIndexRoute
  AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute: typeof AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute
}

const AuthedPlayChildIdRouteChildren: AuthedPlayChildIdRouteChildren = {
  AuthedPlayChildIdResultsRoute: AuthedPlayChildIdResultsRoute,
  AuthedPlayChildIdSpellingRoute: AuthedPlayChildIdSpellingRoute,
  AuthedPlayChildIdIndexRoute: AuthedPlayChildIdIndexRoute,
  AuthedPlayChildIdGamesGobbleRoute: AuthedPlayChildIdGamesGobbleRoute,
  AuthedPlayChildIdMathTopicRoute: AuthedPlayChildIdMathTopicRoute,
  AuthedPlayChildIdGamesIndexRoute: AuthedPlayChildIdGamesIndexRoute,
  AuthedPlayChildIdMathIndexRoute: AuthedPlayChildIdMathIndexRoute,
  AuthedPlayChildIdGamesRoxyHomeRoute: AuthedPlayChildIdGamesRoxyHomeRoute,
  AuthedPlayChildIdGamesRoxyLooksRoute: AuthedPlayChildIdGamesRoxyLooksRoute,
  AuthedPlayChildIdGamesRoxyTownRoute: AuthedPlayChildIdGamesRoxyTownRoute,
  AuthedPlayChildIdRoundListIdModeRoute: AuthedPlayChildIdRoundListIdModeRoute,
  AuthedPlayChildIdGamesRoxyIndexRoute: AuthedPlayChildIdGamesRoxyIndexRoute,
  AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute:
    AuthedPlayChildIdGamesRoxyPlacePlaceIdRoute,
}

const AuthedPlayChildIdRouteWithChildren =
  AuthedPlayChildIdRoute._addFileChildren(AuthedPlayChildIdRouteChildren)

interface AuthedRouteChildren {
  AuthedParentRoute: typeof AuthedParentRouteWithChildren
  AuthedProfilesRoute: typeof AuthedProfilesRoute
  AuthedPlayChildIdRoute: typeof AuthedPlayChildIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedParentRoute: AuthedParentRouteWithChildren,
  AuthedProfilesRoute: AuthedProfilesRoute,
  AuthedPlayChildIdRoute: AuthedPlayChildIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
